const assert = require('node:assert/strict')
const { test } = require('node:test')
const fs = require('node:fs')
const os = require('node:os')
const path = require('node:path')
const { spawnSync } = require('node:child_process')
const { runGate, validateBaseline, formatResult } = require('./typecheck-gate.cjs')

function fixture(t, node = 'export const value: string = 1\n', web = 'export const value = true\n') {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'typecheck-ratchet-'))
  t.after(() => { assert.ok(root.startsWith(path.join(os.tmpdir(), 'typecheck-ratchet-'))); fs.rmSync(root, { recursive: true, force: true }) })
  fs.mkdirSync(path.join(root, 'scripts'))
  fs.writeFileSync(path.join(root, 'tsconfig.json'), JSON.stringify({ files: [], references: [{ path: './tsconfig.node.json' }, { path: './tsconfig.web.json' }] }))
  for (const project of ['node', 'web']) {
    fs.mkdirSync(path.join(root, project))
    fs.writeFileSync(path.join(root, `tsconfig.${project}.json`), JSON.stringify({ compilerOptions: { strict: true, skipLibCheck: true, target: 'ES2022', lib: ['ES5'], types: [], noEmit: false }, include: [`${project}/**/*.ts`] }))
    fs.writeFileSync(path.join(root, project, 'source.ts'), project === 'node' ? node : web)
  }
  const baseline = path.join(root, 'scripts', 'typecheck-baseline.json')
  return { root, baseline, run: mode => runGate({ root, mode }), source: (project, content) => fs.writeFileSync(path.join(root, project, 'source.ts'), content) }
}

test('solution root files: [] still checks real Node and Web; exact baseline passes without emitting', t => {
  const f = fixture(t), bootstrapped = f.run('bootstrap')
  assert.equal(bootstrapped.status, 'BOOTSTRAPPED')
  assert.deepEqual(bootstrapped.checked.map(p => p.project), ['node', 'web'])
  assert.ok(bootstrapped.checked.every(p => p.roots > 0 && p.files > 0))
  assert.equal(bootstrapped.checked[0].diagnostics, 1)
  const before = fs.readFileSync(f.baseline, 'utf8')
  assert.equal(f.run('check').status, 'PASS')
  assert.equal(fs.readFileSync(f.baseline, 'utf8'), before)
  assert.equal(fs.existsSync(path.join(f.root, 'node', 'source.js')), false)
  assert.match(formatResult(bootstrapped), /node: 1 source files/)
  assert.equal(f.run('bootstrap').exitCode, 1)
  assert.equal(fs.readFileSync(f.baseline, 'utf8'), before)
})

test('new identity fails even if total debt stays constant; update cannot bless it', t => {
  const f = fixture(t)
  assert.equal(f.run('bootstrap').exitCode, 0)
  const before = fs.readFileSync(f.baseline, 'utf8')
  f.source('node', 'export const value = true\nunknownIdentifier()\n')
  const result = f.run('check')
  assert.equal(result.status, 'NEW_DIAGNOSTICS')
  assert.equal(result.added[0].code, 2304)
  assert.equal(result.checked[0].diagnostics, 1)
  assert.equal(f.run('update').status, 'NEW_DIAGNOSTICS')
  assert.equal(fs.readFileSync(f.baseline, 'utf8'), before)
})

test('same-identity occurrence growth fails and line movement does not change identity', t => {
  const f = fixture(t)
  f.run('bootstrap')
  f.source('node', '\n\nexport const renamed: string = 1\n')
  assert.equal(f.run('check').status, 'PASS')
  f.source('node', 'export const one: string = 1\nexport const two: string = 2\n')
  const result = f.run('check')
  assert.equal(result.status, 'NEW_DIAGNOSTICS')
  assert.equal(result.added[0].previousCount, 1)
  assert.equal(result.added[0].count, 2)
  const before = fs.readFileSync(f.baseline, 'utf8')
  assert.equal(f.run('update').exitCode, 1)
  assert.equal(fs.readFileSync(f.baseline, 'utf8'), before)
})

test('reduction fails check without mutation and explicit update accepts only a strict subset', t => {
  const f = fixture(t)
  f.run('bootstrap')
  const before = fs.readFileSync(f.baseline, 'utf8')
  f.source('node', 'export const value: string = "fixed"\n')
  const result = f.run('check')
  assert.equal(result.status, 'REDUCTION_REQUIRED')
  assert.equal(result.exitCode, 1)
  assert.equal(fs.readFileSync(f.baseline, 'utf8'), before)
  assert.match(formatResult(result), /npm run typecheck:baseline/)
  const updated = f.run('update')
  assert.equal(updated.status, 'BASELINE_REDUCED', updated.reason)
  assert.deepEqual(JSON.parse(fs.readFileSync(f.baseline, 'utf8')).diagnostics, [])
  assert.equal(f.run('check').status, 'PASS')
  assert.equal(f.run('update').status, 'NO_REDUCTION')
})

test('project identity distinguishes equal messages in Node and Web', t => {
  const f = fixture(t)
  f.run('bootstrap')
  f.source('node', 'export const value = 1\n')
  f.source('web', 'export const value: string = 1\n')
  const result = f.run('check')
  assert.equal(result.status, 'NEW_DIAGNOSTICS')
  assert.equal(result.added[0].project, 'web')
  assert.equal(result.reduced[0].project, 'node')
})

test('occurrences can ratchet down without deleting an identity', t => {
  const f = fixture(t, 'export const one: string = 1\nexport const two: string = 2\n')
  f.run('bootstrap')
  f.source('node', 'export const one: string = 1\n')
  assert.equal(f.run('check').status, 'REDUCTION_REQUIRED')
  assert.equal(f.run('update').status, 'BASELINE_REDUCED')
  assert.equal(JSON.parse(fs.readFileSync(f.baseline, 'utf8')).diagnostics[0].count, 1)
  assert.equal(f.run('check').status, 'PASS')
})

test('file identity prevents moving a known error and the CLI returns failure', t => {
  const f = fixture(t)
  f.run('bootstrap')
  f.source('node', 'export const value = true\n')
  fs.writeFileSync(path.join(f.root, 'node', 'other.ts'), 'export const value: string = 1\n')
  const result = f.run('check')
  assert.equal(result.status, 'NEW_DIAGNOSTICS')
  assert.equal(result.added[0].file, 'node/other.ts')
  const cli = spawnSync(process.execPath, [path.join(__dirname, 'typecheck-gate.cjs')], { cwd: f.root, encoding: 'utf8', windowsHide: true })
  assert.equal(cli.status, 1, cli.stderr)
  assert.match(cli.stdout, /Typecheck baseline: NEW_DIAGNOSTICS/)
})

test('zero-code project and invalid config cannot be bootstrapped or baseline-updated', t => {
  const f = fixture(t)
  f.run('bootstrap')
  const before = fs.readFileSync(f.baseline, 'utf8')
  fs.writeFileSync(path.join(f.root, 'web', 'empty.d.ts'), '')
  fs.writeFileSync(path.join(f.root, 'tsconfig.web.json'), JSON.stringify({ compilerOptions: { types: [], lib: ['ES5'] }, files: ['web/empty.d.ts'] }))
  assert.match(f.run('check').reason, /ZERO_FILES web/)
  assert.equal(f.run('update').exitCode, 1)
  assert.equal(fs.readFileSync(f.baseline, 'utf8'), before)
  fs.writeFileSync(path.join(f.root, 'tsconfig.web.json'), '{ invalid json')
  assert.match(f.run('check').reason, /INVALID_CONFIG web/)
  fs.unlinkSync(f.baseline)
  assert.equal(f.run('bootstrap').exitCode, 1)
  assert.equal(fs.existsSync(f.baseline), false)
})

test('invalid compiler options fail structurally before the baseline can accept them', t => {
  const f = fixture(t)
  fs.writeFileSync(path.join(f.root, 'tsconfig.web.json'), JSON.stringify({ compilerOptions: { paths: { alias: ['web/source.ts'] } }, include: ['web/*.ts'] }))
  assert.match(f.run('bootstrap').reason, /INVALID_CONFIG web: TS5090/)
  assert.equal(fs.existsSync(f.baseline), false)
})

test('rootDir must cover transitive source files, not just configured roots', t => {
  const f = fixture(t, 'import { value } from "../outside"\nexport { value }\n')
  fs.writeFileSync(path.join(f.root, 'outside.ts'), 'export const value = true\n')
  fs.writeFileSync(path.join(f.root, 'tsconfig.node.json'), JSON.stringify({ compilerOptions: { rootDir: 'node', types: [], lib: ['ES5'] }, include: ['node/*.ts'] }))
  assert.match(f.run('bootstrap').reason, /INVALID_CONFIG node/)
  assert.equal(fs.existsSync(f.baseline), false)
})

test('baseline missing, malformed or duplicated and unexpected compiler failures fail closed', t => {
  const f = fixture(t)
  assert.match(f.run('check').reason, /BASELINE_MISSING/)
  assert.match(f.run('update').reason, /BASELINE_MISSING/)
  fs.writeFileSync(f.baseline, '{bad json')
  assert.equal(f.run('check').exitCode, 1)
  assert.throws(() => validateBaseline({ version: 1, diagnostics: [{ project: 'node', count: 0 }] }), /INVALID_BASELINE/)
  fs.unlinkSync(f.baseline); f.run('bootstrap')
  const baseline = JSON.parse(fs.readFileSync(f.baseline, 'utf8'))
  assert.throws(() => validateBaseline({ ...baseline, diagnostics: [...baseline.diagnostics, ...baseline.diagnostics] }), /duplicate diagnostic identity/)
  const diagnostic = baseline.diagnostics[0]
  for (const value of [{ ...diagnostic, file: '/absolute.ts' }, { ...diagnostic, file: '../outside.ts' }, { ...diagnostic, category: 'invalid' }, { ...diagnostic, count: -1 }]) assert.throws(() => validateBaseline({ version: 1, diagnostics: [value] }), /INVALID_BASELINE/)
  assert.match(runGate({ root: f.root, compiler: () => { throw new Error('compiler failed') } }).reason, /compiler failed/)
})
