const fs = require('node:fs')
const path = require('node:path')
const { buildSync } = require('esbuild')
exports.run = async ctx => {
  const entry = path.join(__dirname, 'continuum-fixture.tsx')
  buildSync({ entryPoints: [entry], bundle: true, outfile: path.join(ctx.temporary, 'fixture.js'), platform: 'browser', jsx: 'automatic', define: { 'process.env.NODE_ENV': '"production"' }, loader: { '.woff': 'dataurl', '.woff2': 'dataurl', '.ttf': 'dataurl' } })
  const page = path.join(ctx.temporary, 'index.html')
  fs.writeFileSync(page, '<!doctype html><html><head><meta charset="utf-8"><link rel="stylesheet" href="fixture.css"><style>html,body,#root{height:100%;margin:0}body{background:var(--bg-primary);color:var(--text-primary)}</style></head><body><div id="root"></div><script src="fixture.js"></script></body></html>')
  await ctx.load(page)
  await ctx.waitFor(() => document.querySelectorAll('.continuum-item').length === 18)
  await ctx.viewport(1440, 900)
  await ctx.click('.continuum-item')
  await ctx.waitFor(() => !!document.querySelector('.continuum-markdown h1'))
  ctx.check('Selection and native focus', await ctx.evaluate(() => document.querySelector('.continuum-item').getAttribute('aria-pressed') === 'true' && document.activeElement.classList.contains('continuum-item')))
  ctx.check('Long content scrolls locally', await ctx.evaluate(() => { const pane = document.querySelector('.continuum-inspector .continuum-pane-scroll'); return pane.scrollHeight > pane.clientHeight }))
  await ctx.overflow()
  await ctx.capture('wide-dark-selected')
  await ctx.evaluate(() => { document.body.dataset.theme = 'light' })
  await ctx.capture('wide-light-selected')
  await ctx.viewport(1000, 760)
  await ctx.overflow()
  await ctx.capture('medium-light-selected')
  await ctx.evaluate(() => { document.body.dataset.theme = 'dark' })
  await ctx.input('[aria-label="Buscar no Continuum"]', 'Observation 12')
  await ctx.waitFor(() => document.querySelectorAll('.continuum-item').length === 1)
  ctx.check('Search retains focus', await ctx.evaluate(() => document.activeElement.getAttribute('aria-label') === 'Buscar no Continuum'))
  await ctx.overflow()
  await ctx.capture('medium-dark-search')
}
